<?php if(!$this->isLoggedIn()){ ?>
<div id="overlay"></div>
<div id="sidebar">
	<ul class="tabs">
		<li class="link tab-register">Register</li>
		<li class="link tab-login active">Sign in</li>
	</ul>
	<div class="bd-register">
		<?php  echo $this->getChildHtml('customer_new'); ?>
	</div>
	<div class="bd-login active">
		<?php  echo $this->getChildHtml('customer_login'); ?>
	</div>
	<div class="bd-forgot">
		<?php  echo $this->getChildHtml('customer_forgot'); ?>
	</div>
	<div class="bd-sent">
        <div class="success-message">
            <svg enable-background="new 0 0 32 32" version="1.1" viewBox="0 0 32 32" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path clip-rule="evenodd" d="M27.704,8.397c-0.394-0.391-1.034-0.391-1.428,0  L11.988,22.59l-6.282-6.193c-0.394-0.391-1.034-0.391-1.428,0c-0.394,0.391-0.394,1.024,0,1.414l6.999,6.899  c0.39,0.386,1.039,0.386,1.429,0L27.704,9.811C28.099,9.421,28.099,8.787,27.704,8.397C27.31,8.006,28.099,8.787,27.704,8.397z"/><g/><g/><g/><g/><g/><g/></svg>
            <div>
            	<p>Link Sent</p>
            	<p>Please check your email</p>
            </div>
        </div>
        <button class="button default">Close</button>
    </div>
</div>
<style type="text/css">
#sidebar {
	position: fixed;
	width: 300px;
	z-index: 1000000;
	background-color: #ededed;
	right: -300px;
	height: 100%;
	-webkit-transition: all 0.5s ease;
  	-moz-transition: all 0.5s ease;
  	-o-transition: all 0.5s ease;
  	-ms-transition: all 0.5s ease;
  	transition: all 0.5s ease;
}
#overlay {
	background-color: rgba(0,0,0,0.8);
	width: 100%;
	height: 100%;
	position: fixed;
	top: 0;
	left: 0;
	z-index: 100000;
	display: none;
}
#sidebar.active{
	right: 0px;
	
}
#overlay.active{
	display: block;
}
#sidebar .tabs {
	padding: 0;
	margin: 0;
	list-style: none;
}
#sidebar .tabs .link {
	display: inline-block;
	width: 50%;
	text-align: center;
	padding: 10px 0;
	margin: 0;
	border-top: 6px solid #c9cacb;
	font-size: 20px;
	background-color: #c9cacb;
	cursor: pointer;
}
#sidebar .tabs .link:hover {
	background-color: #d6d7d8;
}
#sidebar .tabs .link:nth-child(1) {
	float: left;
}
#sidebar .tabs .link.active {
	border-color: #1af;
	background-color: #ededed;
	cursor: default;
}
#sidebar .tabs .link.active:hover{
	background-color: #ededed;
}
#sidebar .bd-register{
	padding: 20px;
	display: none;
}
#sidebar .bd-register.active{
	display: block;
}
#sidebar .bd-login{
	padding: 20px;
	display: none;
}
#sidebar .bd-login.active{
	display: block;
}
#sidebar .bd-forgot{
	padding: 20px;
	display: none;
}
#sidebar .bd-sent {
	padding: 20px;
}
#sidebar .bd-sent{
	padding: 20px;
	display: none;
}
#sidebar .bd-sent.active{
	display: block;
}
#sidebar .bd-sent .success-message {
	text-align: center;
	color: #00a14b;
}
#sidebar .bd-sent .success-message svg {
	font-size: 20px;
	width: 100px;
	height: 100px;
	border: 2px solid #00a14b;
	fill: #00a14b;
	border-radius: 54px;
}
#sidebar .bd-sent .success-message div{
	
}
#sidebar .bd-forgot.active{
	display: block;
}
#sidebar .error-message {
	color: #f26522;
	margin-bottom: 20px;
	font-size: 14px;
	font-weight: 600;
}
#sidebar .action.primary {
	background-color: #3b95c7;
	color: white;
	border-radius: 3px;
	width:100%;
}
#sidebar .fieldset > .field:not(.choice) > .label, #sidebar .fieldset > .field:not(.choice) > .control {
	width: unset;
	float: unset;
}
#sidebar .fieldset > .field > .label {
	margin: 0 0 8px;
}

body.sidebar-open {
	overflow: hidden;
}

ul.check {
  list-style: none;
}

ul.check li:before {
  content: '✓';
}
.bd-register .block-title,
.form-login .actions-toolbar .primary,
.form-login .actions-toolbar .secondary {padding-bottom:15px;}
#block-new-customer-heading {text-decoration:underline;}

.form-login .actions-toolbar .primary,
.form-login .actions-toolbar .secondary,
.block-new-customer .actions-toolbar .primary,
.block-new-customer .actions-toolbar .secondary {width:100%;}
#sidebar .field.rememberme .control {
	display: inline-block;
	position: relative;
	top: 2px;
}
.block-new-customer ul.check {
	padding-left: 0px;
}
.block-new-customer .primary{
	margin-bottom: 15px;
}
</style>
<script type="text/javascript">
require(['jquery'], function($){
	var formSubmitted = false;
	var formForgotSubmitted = false;
  	$( ".authorization-link a" ).click(function( event ) {
	  	event.preventDefault();
	  	$('#sidebar').addClass('active');
	  	$('#overlay').addClass('active');
	  	$('body').addClass('sidebar-open');

	  	$('.bd-register').hide();
  		$('.bd-login').show();
  		$('.bd-forgot').hide();
  		$('.bd-sent').hide();
	});
	$( "#overlay" ).click(function( event ) {
	  	$('#sidebar').removeClass('active');
	  	$('#overlay').removeClass('active');
	  	$('body').removeClass('sidebar-open');
	});
	$( "#sidebar .cancel" ).click(function( event ) {
	  	$('#sidebar').removeClass('active');
	  	$('#overlay').removeClass('active');
	  	$('body').removeClass('sidebar-open');
	});


	$("#sidebar .tab-register").click(function( event ) {
	  	var currentElement = $(this);
	  	if(!currentElement.hasClass('active')){
	  		currentElement.addClass('active');
	  		$("#sidebar .tab-login").removeClass('active');
	  		$('.bd-register').show();
	  		$('.bd-login').hide();
	  		$('.bd-forgot').hide();
	  		$('.bd-sent').hide();
	  	}
	});
	$("#sidebar .tab-login").click(function( event ) {
	  	var currentElement = $(this);
	  	if(!currentElement.hasClass('active')){
	  		currentElement.addClass('active');
			$("#sidebar .tab-register").removeClass('active');

	  		$('.bd-login').show();
	  		$('.bd-register').hide();
	  		$('.bd-forgot').hide();
	  		$('.bd-sent').hide();
	  	}
	});
	$( ".actions-toolbar .secondary a.action.remind" ).click(function( event ) {
	  	event.preventDefault();
	  	$("#sidebar .tab-register").removeClass('active');
	  	$("#sidebar .tab-login").removeClass('active');
	  	$('.bd-register').hide();
	  	$('.bd-login').hide();
	  	$('.bd-sent').hide();
	  	$('.bd-forgot').show();
	});
	
	$( ".bd-sent button" ).click(function( event ) {
	  	$('#sidebar').removeClass('active');
	  	$('#overlay').removeClass('active');
	  	$('body').removeClass('sidebar-open');
	});
	$("#login-form").submit(function(e) {
		if(formSubmitted){
		} else {
			e.preventDefault();
	        var form = $(this);
	        var url = "<?php echo $this->getUrl('loginsidebar'); ?>";
	        $.ajax({
	            type: "POST",
	            url: url,
	            data: form.serialize(),
	            success: function(data)
	            {
	                if(data.success){
	                	formSubmitted = true;
	                	$("#login-form").submit();
	                }else{
	                	$('.form-login .error-message').first().html(data.message);
	                }
	            }
	        });
		}
    });
    $("#form-forgot").submit(function(e) {
		if(formForgotSubmitted){
		} else {
			e.preventDefault();
	        var form = $(this);
	        var url = "<?php echo $this->getUrl('loginsidebar/index/forgot'); ?>";
	        $.ajax({
	            type: "POST",
	            url: url,
	            data: form.serialize(),
	            success: function(data)
	            {
	            	console.log(data);
	                if(data.success){
	                	formForgotSubmitted = true;
	                	$('.bd-forgot').hide();
	                	$('.bd-sent').show();
	                }else{
	                	$('#form-forgot .error-message').first().html(data.message);
	                }
	            },
			    error: function (xhr, status, errorThrown) {
			    	console.log(xhr.status);
			        console.log(xhr.responseText);
			    }
	        });
		}
    });
});
</script>
<?php } ?>